#! /bin/bash

d="/home/Videos/YouTube"
i="$(echo "$1" | sed -e "s/savetube://" -e "s/SEPARATOR/|/g")"
t="$(echo "$i" | cut -d "|" -f 1 | sed -e "s/%20/ /g" -e "s/ +$//" -e "s/^ +//")"
v="$(echo "$i" | cut -d "|" -f 2)"
a="$(echo "$i" | cut -d "|" -f 3)"
f="$(echo "$v" | grep -q "video/web\|\.webm" && echo "webm" || echo "mp4")"
if [ "$a" = "" ]; then
	if echo "$v" | grep -qi "\.m3u8"; then
		ffmpeg -y -i "$v" -c copy "$d/$t.$f"
	else
		youtube-dl "$v" -o "$d/$t"
	fi
else
	ffmpeg -y -i "$v" -i "$a" -c copy "$d/$t.$f"
fi
